# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2238dc6b197dccc9fbf1721bb0aaddb91c57839ab71a2646634378d1449fcfbbbd8c27d04dabd7145d7a644d61352ec20b8963c4aa1850d19a6f18b38929e97

test:
  secret_key_base: fc358e1b6b89fd4fb5ae99b6bfe0d5058e7e48c9db075a056208258eabfc1d802b7f89972fc04a8d47894e8ecadf010f64276adadc2c993e55ec3c482ddfd407

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
